### ISSUE TITLE
no v3 db.json

### ISSUE THREAD

**Issue by darkst0rm223** [mocchapi/pesterchum-themes#3]
**Describe the bug**
i attempted to use the theme manager but there's no v3

**To Reproduce**
1. Go to idle/updates
2. Change theme database url
3. go install themes
4. it will complain

**Expected behavior**
themes would show up

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux

**Additional context**

**Comment by mocchapi** [comment]
oh huh. looks like main branch is mislabeled as v2 still. oops
thanks for mentioning it
